<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="499e8550-9a1c-43a0-9d80-d8a72680918d" name="jjepson@ECONET0638 2017-08-16 18:52:58" runUser="UNIVERA\jjepson" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="67aa6120-b7cb-4834-b9e9-fdcf8b6bc7e9">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="jjepson_ECONET0638 2017-08-16 18_52_58">
      <DeploymentItem filename="C:\Code\LinkedListExercise\LinkedListExercise\bin\Debug\LinkedListExercise.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2017-08-16T18:52:58.4975846-07:00" queuing="2017-08-16T18:52:59.2653509-07:00" start="2017-08-16T18:52:59.4319524-07:00" finish="2017-08-16T18:58:59.2566507-07:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="TestIntersection" storage="c:\code\linkedlistexercise\linkedlistexcercisetest\bin\debug\linkedlistexcercisetest.dll" id="8b7ce42e-1080-f346-a16b-c47d0afab538">
      <Execution id="56d1cba2-e1fc-48de-ba14-8e556c862786" />
      <TestMethod codeBase="C:/Code/LinkedListExercise/LinkedListExcerciseTest/bin/Debug/LinkedListExcerciseTest.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="LinkedListExcerciseTest.LinkedListTest, LinkedListExcerciseTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="TestIntersection" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="8b7ce42e-1080-f346-a16b-c47d0afab538" executionId="56d1cba2-e1fc-48de-ba14-8e556c862786" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="56d1cba2-e1fc-48de-ba14-8e556c862786" testId="8b7ce42e-1080-f346-a16b-c47d0afab538" testName="TestIntersection" computerName="ECONET0638" duration="00:05:58.4733930" startTime="2017-08-16T18:52:59.5620486-07:00" endTime="2017-08-16T18:58:59.1892615-07:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="56d1cba2-e1fc-48de-ba14-8e556c862786">
      <Output>
        <ErrorInfo>
          <Message>Test method LinkedListExcerciseTest.LinkedListTest.TestIntersection threw exception: 
System.InvalidOperationException: The LinkedList node already belongs to a LinkedList.</Message>
          <StackTrace>    at System.Collections.Generic.LinkedList`1.ValidateNewNode(LinkedListNode`1 node)
   at System.Collections.Generic.LinkedList`1.AddLast(LinkedListNode`1 node)
   at LinkedListExcerciseTest.LinkedListTest.TestIntersection() in C:\Code\LinkedListExercise\LinkedListExcerciseTest\LinkedListTest.cs:line 50
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>